version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stable-curl-browsers-legacy
    steps:
      - checkout
      - run:
          name: Pack
          command: zip -r resourcepack.zip ./*
      - run:
          name: Create pack folder
          command: mkdir packed/
      - run:
          name: Create pack folder
          command: mv resourcepack.zip packed/
      - run:
          name: Calculate sha1 checksum
          command: sha1sum packed/resourcepack.zip
      - store_artifacts:
          path: packed/
          destination: .
